version: '3.9'

services:
  api:
    build: ./django-crud-api
    ports:
      - 8880:80
    depends_on:
      - statsd-exporter

  locust-master:
    build: 
      context: ./locust-tests
      dockerfile: master.dockerfile
    depends_on:
      - api
    ports:
      - 8881:8881

  locust-worker:
    build:
      context: ./locust-tests
      dockerfile: worker.dockerfile
    depends_on:
      - api
      - locust-master
    deploy:
      mode: replicated
      replicas: 5

  locust-exporter:
    build: ./prometheus/exporters/locust
    ports:
      - "8883:8883"

  statsd-exporter:
    build: ./prometheus/exporters/statsd
    ports:
      - "8884:9102"

  prometheus:
    build: ./prometheus
    ports:
      - 8885:9090
    depends_on:
      - statsd-exporter
      - locust-exporter

  grafana:
    build: ./grafana
    ports:
      - 8886:3000
    depends_on:
      - prometheus
