global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:

  - job_name: 'statsd-exporter'
    static_configs:
      - targets: ['statsd-exporter:9102']

  - job_name: 'locust-exporter'
    static_configs:
      - targets: ['locust-exporter:8883']
      