{
 "title": "Gunicorn - Django REST API",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "rate(gunicorn_requests[1m])", "legendFormat": "requests" }
   ]
  },
  {
   "title": "HTTP Status Codes",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "rate(gunicorn_request_status_200[1m])",
     "legendFormat": "200"
    },
    {
     "expr": "rate(gunicorn_request_status_201[1m])",
     "legendFormat": "201"
    },
    {
     "expr": "rate(gunicorn_request_status_204[1m])",
     "legendFormat": "204"
    },
    {
     "expr": "rate(gunicorn_request_status_404[$__rate_interval])",
     "legendFormat": "404"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 11 },
   "targets": [
    { "expr": "gunicorn_request_duration", "legendFormat": "{{__name__}}_{{quantile}}" }
   ]
  }
 ]
}